version: '3'

services:

  wordpress:
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=cloud-final.cy8x8vyjtlwm.us-east-1.rds.amazonaws.com:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress_docker
    volumes:
      - type: bind
        source: /var/lib/efs/wordpress
        target: /var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/lib/efs/wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge